matrix:
  SCALA_VERSION:
    - 2.10.5
    - 2.11.6
  TEST_SUITE:
    - test
    - it:test

cache:
  mount:
    - /drone/.coursier/cache/v1
    - /drone/.sbt/boot
    - /drone/.sbt/launchers

build:
  image: ensime/ensime:v2.x
  pull: true
  environment:
    - CACHE_DIR="/drone"
    - SCALATEST_SPAN_SCALE_FACTOR=10
  commands:
    - mkdir -p $CACHE_DIR/.coursier
    - mkdir -p $CACHE_DIR/.sbt
    - cp -a $CACHE_DIR/.coursier $HOME
    - cp -a $CACHE_DIR/.sbt $HOME
    - rm -rf $CACHE_DIR/.coursier
    - rm -rf $CACHE_DIR/.sbt
    - javac -version
    - /usr/bin/sbt ++$SCALA_VERSION "$TEST_SUITE"
    - cp -a $HOME/.coursier $CACHE_DIR
    - cp -a $HOME/.sbt $CACHE_DIR

