matrix:
  SCALA_VERSION:
    - 2.10.6
    - 2.11.8
  TEST_SUITE:
    - test it:test

build:
  image: chipsenkbeil/scala-debugger:latest
  pull: true
  environment:
    - CACHE_DIR="/drone"
    - SCALATEST_SPAN_SCALE_FACTOR=10
  commands:
    - javac -version
    - /usr/bin/sbt ++$SCALA_VERSION $TEST_SUITE

