site_name: Scala Debugger
site_url: http://www.scala-debugger.org
site_description: API and tooling for the JVM using Scala.
site_author: Chip Senkbeil
site_favicon: /img/favicon.ico

repo_url: https://github.com/chipsenkbeil/scala-debugger-api/

google_analytics: ['UA-71733200-1', 'scala-debugger.org']

pages:
    - Home: index.md
    - Getting Started:
        - What is a Debugger?: getting-started/what-is-a-debugger.md
        - Installation: getting-started/installation.md
        - Available Debugger Connections: getting-started/available-debugger-connections.md
        - Event Pipelines: getting-started/event-pipelines.md
        - Working with Breakpoints: getting-started/working-with-breakpoints.md
        - Stepping through Code: getting-started/stepping-through-code.md
        - Watching class variables: getting-started/watching-class-variables.md
    - Advanced Topics:
        - What is the Profile System?: advanced-topics/what-is-the-profile-system.md
        - What is the Low-Level API?: advanced-topics/what-is-the-low-level-api.md
        - Using Extra Arguments for Requests: advanced-topics/using-extra-arguments-for-requests.md
        - Making Requests Early: advanced-topics/making-requests-early.md
    - Cookbook:
        - Creating a Launching Debugger: cookbook/creating-a-launching-debugger.md
        - Creating an Attaching Debugger: cookbook/creating-an-attaching-debugger.md
        - Creating a Listening Debugger: cookbook/creating-a-listening-debugger.md
        - Creating a Breakpoint: cookbook/creating-a-breakpoint.md
        - Stepping over a Line of Code: cookbook/stepping-over-a-line-of-code.md
        - Watching Modification of a Class Variable: cookbook/watching-modification-of-a-class-variable.md
    - Scaladoc:
        - Scaladoc 2.10: external/scaladoc-2.10.md
        - Scaladoc 2.11: external/scaladoc-2.11.md
    - About:
        - Roadmap: about/roadmap.md
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - attr_list
    - abbr

copyright: Copyright &copy; 2015 <a href="http://chipsenkbeil.com">Chip Senkbeil</a>.

